name: Flutter Windows CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.24.0'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Windows executable
      run: flutter build windows

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
      
        name: app-release
        path: ${{github.workspace}}/build/windows/x64/runner/Release/random_roll_call.exe
        if-no-files-found: warn
        retention-days: 30
